### ISSUE TITLE
No module named "six"

### ISSUE THREAD

**Issue by HellodWorlD** [riga/numphy#2]
C:\Users\Hello>pip install numphy
Collecting numphy
  Using cached https://files.pythonhosted.org/packages/7f/1c/595b4f68889f6fb249506a96b9db1ef4051ef75c0d940489d0436ced930a/numphy-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hello\AppData\Local\Temp\pip-install-8bn6iepj\numphy\setup.py", line 7, in <module>
        import numphy as nph
      File "C:\Users\Hello\AppData\Local\Temp\pip-install-8bn6iepj\numphy\numphy\__init__.py", line 26, in <module>
        from numphy.core import *
      File "C:\Users\Hello\AppData\Local\Temp\pip-install-8bn6iepj\numphy\numphy\core.py", line 18, in <module>
        from numphy.util import no_value, is_lazy_iterable
      File "C:\Users\Hello\AppData\Local\Temp\pip-install-8bn6iepj\numphy\numphy\util.py", line 14, in <module>
        import six
    ModuleNotFoundError: No module named 'six'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Hello\AppData\Local\Temp\pip-install-8bn6iepj\numphy\

**Comment by erikgeiser** [comment]
This should be easily fixable as the numphy import in the setup.py is only used to get meta information.

In the meantime you could just install six by hand with `pip install six`. Afterwards it should be possible to install numphy.

**Comment by HellodWorlD** [comment]
1.print("Thank you it worked.")
